name: jarab_lawnuk
description: تطبيق لتجربة ألوان الطلاء على صور الغرف

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.5
  # إدارة الحالة
  provider: ^6.0.5
  # معالجة الصور
  image_picker: ^1.0.4
  image: ^4.1.3
  path_provider: ^2.1.1
  # الذكاء الاصطناعي ومعالجة الصور
  tflite_flutter: ^0.10.3
  # الإشعارات
  firebase_core: ^2.17.0
  firebase_messaging: ^14.6.9
  flutter_local_notifications: ^17.2.0  # Update from 16.1.0 to 17.2.0 or later
  # التخزين المحلي
  shared_preferences: ^2.2.1
  hive: ^2.2.3
  hive_flutter: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.3
  hive_generator: ^2.0.1
  build_runner: ^2.4.6

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/Ne/
    - assets/models/
  fonts:
    - family: Cairo
      fonts:
        - asset: assets/fonts/Cairo-Regular.ttf
        - asset: assets/fonts/Cairo-Bold.ttf
          weight: 700
